# -*- coding: utf-8 -*-
"""
Created on Thu Feb 12 14:04:27 2026

@author: marco

Expanded Analysis: Realized Volatility, VIX, and Regression Analysis
"""

import datetime as dt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas_datareader import data as pdr
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint
import yfinance as yf  # The minimal fix for reliable data

# -----------------------------
# 1. Data Fetching Functions
# -----------------------------

def download_spx_ohlc_stooq(start_date: str, end_date: str) -> pd.DataFrame:
    """
    Download daily OHLCV for S&P 500 from Stooq.
    Stooq ticker for S&P 500 is usually '^SPX' or 'SPX.US'.
    """
    start = pd.to_datetime(start_date)
    end = pd.to_datetime(end_date)
    
    # List of likely tickers for SPX on Stooq
    candidates = ["^SPX", "SPX.US"]
    
    last_err = None
    for t in candidates:
        try:
            df = pdr.DataReader(t, "stooq", start, end)
            if df is not None and not df.empty:
                df = df.sort_index()
                df.index = pd.to_datetime(df.index)
                # Ensure all columns are numeric
                for col in ['Open', 'High', 'Low', 'Close']:
                     df[col] = pd.to_numeric(df[col], errors='coerce')
                return df
        except Exception as e:
            last_err = e

    print(f"Warning: Could not fetch SPX OHLC. Last error: {last_err}")
    return pd.DataFrame()

def fetch_vix_close(start_date, end_date):
    """
    Fetch daily VIX close series.
    Primary: FRED VIXCLS (Cleanest source)
    Fallback: Stooq
    """
    start = pd.to_datetime(start_date)
    end = pd.to_datetime(end_date)
    
    # Try FRED first
    try:
        df = pdr.DataReader("VIXCLS", "fred", start, end)
        df = df.rename(columns={"VIXCLS": "VIX_Close"}).dropna()
        df.index = pd.to_datetime(df.index)
        return df
    except Exception:
        print("FRED VIX fetch failed, trying Stooq...")
    
    # Fallback: Stooq
    for sym in ["VI.F", "^VIX"]:
        try:
            df = pdr.DataReader(sym, "stooq", start, end)
            df = df.sort_index()
            df.index = pd.to_datetime(df.index)
            if "Close" in df.columns and not df.empty:
                return df[["Close"]].rename(columns={"Close": "VIX_Close"}).dropna()
        except Exception:
            continue
    return pd.DataFrame()

# -----------------------------
# 2. Main Execution & Calculations
# -----------------------------

# Parameters
ticker = "SPX"
start_date = "2015-01-01"
end_date = dt.date.today().strftime("%Y-%m-%d")
window_size = 30  # 30-day rolling window for realized vol

print(f"Fetching data from {start_date} to {end_date}...")

# A. Get Data
spx_data = download_spx_ohlc_stooq(start_date, end_date)
vix_data = fetch_vix_close(start_date, end_date)

if spx_data.empty or vix_data.empty:
    raise RuntimeError("Failed to download necessary data (SPX or VIX). Check internet or tickers.")


# Compute Realized Estimators on SPX

# 1. Classical Volatility (Std Dev of Close-to-Close returns)
spx_data['Return'] = spx_data['Close'].pct_change()
spx_data['Realized_Classical'] = spx_data['Return'].rolling(window=window_size).std() * np.sqrt(252) * 100

# 3. Garman-Klass Estimator (OHLC)
# Uses Open, High, Low, Close for better efficiency than Parkinson
log_hl = np.log(spx_data['High'] / spx_data['Low'])**2
log_co = np.log(spx_data['Close'] / spx_data['Open'])**2
spx_data['GK_Var'] = 0.5 * log_hl - (2 * np.log(2) - 1) * log_co
spx_data['Realized_GK'] = np.sqrt(spx_data['GK_Var'].rolling(window=window_size).mean()) * np.sqrt(252) * 100

# Merge Data
# We align the indices. VIX is already in percentage points (e.g., 20.0), 
# so we multiplied realized vols by 100 above to match scale.
combined = spx_data.join(vix_data, how='inner')

# Prepare Regression Variables (Variations)
# We analyze how Returns interact with CHANGES in volatility
combined['VIX_Diff'] = combined['VIX_Close'].diff()
combined['Realized_GK_Diff'] = combined['Realized_GK'].diff()

# Drop NaNs generated by rolling windows and diffs
analysis_df = combined.dropna()

# -----------------------------
# 3. Regression Analysis
# -----------------------------
print("\n" + "="*50)
print("Regression Analysis")
print("="*50)


# Regression 1: SPX Returns vs. VIX Variations
# Hypothesis: Strong Negative Correlation (Leverage Effect/Fear Gauge)
X1 = analysis_df['VIX_Diff']
Y = analysis_df['Return']
X1 = sm.add_constant(X1) # Add intercept

model_vix = sm.OLS(Y, X1).fit()

print("\n" + "-"*30)
print("REGRESSION 1: SPX Return ~ Delta VIX")
print("-"*30)
print(model_vix.summary().tables[1])
beta_vix = model_vix.params['VIX_Diff']
r2_vix = model_vix.rsquared

# Regression 2: SPX Returns vs. Realized Vol Variations
# Hypothesis: Weaker Correlation (Backward looking vs Forward looking)
X2 = analysis_df['Realized_GK_Diff']
X2 = sm.add_constant(X2)

model_rv = sm.OLS(Y, X2).fit()

print("\n" + "-"*30)
print("REGRESSION 2: SPX Return ~ Delta Realized Vol (GK)")
print("-"*30)
print(model_rv.summary().tables[1])
beta_rv = model_rv.params['Realized_GK_Diff']
r2_rv = model_rv.rsquared


# -----------------------------
# 4. Plotting
# -----------------------------
plt.figure(figsize=(14, 8))


# Subplot 1: Scatter of Regression 1
plt.subplot(2, 1, 1)
plt.scatter(analysis_df['VIX_Diff'], analysis_df['Return'], alpha=0.4, color='red', s=10, label='Data Points')
# Plot regression line
x_range = np.linspace(analysis_df['VIX_Diff'].min(), analysis_df['VIX_Diff'].max(), 100)
y_pred = model_vix.params['const'] + model_vix.params['VIX_Diff'] * x_range
plt.plot(x_range, y_pred, color='blue', linewidth=2, label=f'Regression Line (Beta={beta_vix:.3f})')
plt.title('Regression: SPX Returns vs. Change in VIX')
plt.xlabel('Change in VIX')
plt.ylabel('SPX Return')
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 2: Scatter of Regression 2
plt.subplot(2, 1, 2)
plt.scatter(analysis_df['Realized_GK_Diff'], analysis_df['Return'], alpha=0.4, color='red', s=10, label='Data Points')
# Plot regression line
x_range = np.linspace(analysis_df['Realized_GK_Diff'].min(), analysis_df['Realized_GK_Diff'].max(), 100)
y_pred = model_rv.params['const'] + model_rv.params['Realized_GK_Diff'] * x_range
plt.plot(x_range, y_pred, color='blue', linewidth=2, label=f'Regression Line (Beta={beta_rv:.3f})')
plt.title('Regression: SPX Returns vs. Change in Realized GK')
plt.xlabel('Change in Realized GK')
plt.ylabel('SPX Return')
plt.legend()
plt.grid(True, alpha=0.3)


plt.tight_layout()
plt.savefig(f'regression_{ticker}.png', dpi=300)
plt.show()


# -----------------------------
# 5. Discussion of Results
# -----------------------------
print("\n" + "="*50)
print("OBSERVATIONS & INTERPRETATION")
print("="*50)
print(f"1. VIX Sensitivity (Beta): {beta_vix:.4f}")
print(f"   Interpretation: For every 1 point increase in VIX, SPX typically moves {beta_vix*100:.2f}%.")
print(f"   R-squared: {r2_vix:.4f} (VIX explains {r2_vix*100:.1f}% of return variance)")
print(f"\n2. Realized Vol Sensitivity (Beta): {beta_rv:.4f}")
print(f"   R-squared: {r2_rv:.4f}")

print("\nKey Insight:")
if abs(beta_vix) > abs(beta_rv) and r2_vix > r2_rv:
    print("-> The VIX (Implied Vol) has a much stronger immediate negative correlation")
    print("   with returns than Realized Volatility.")
    print("-> Reason: VIX is forward-looking and prices in 'fear' instantly.")
    print("-> Realized Vol is backward-looking (moving average), smoothing out the shock.")


